// For thorough documentation, see the examples at https://github.com/etsy/statsd/

{
graphiteHost: "graphite.example.com",
graphitePort: 2003,
port: 8125,
backends: [ "./backends/graphite" ],
// debug: false,
// address: '0.0.0.0',
// address_ipv6: false,
// mgmt_address: '0.0.0.0',
// mgmt_port: 8126,
// title: statsd,
// healthStatus: 'up',
// dumpMessages: false,
// flushInterval: 100,
// percentThreshold: 90,
// flush_counts: true,
// keyFlush: { interval: 0, percent: 100, log: 'STDOUT' },
// deleteIdleStats: false,
// deleteGauges: false,
// deleteTimers: false,
// deleteSets: false,
// deleteCounters: false,
// prefixStats: 'statsd',
// console: { prettyprint: true },
// log: { backend: 'stdout', application: 'statsd', level: 'LOG_INFO' },
// graphite: { legacyNamespace: true, globalPrefix: 'stats', prefixCounter: 'counters', prefixTimer: 'timers',  prefixGauge: 'gauges', prefixSet: 'sets', globalSuffix: '' },
// repeater: { host: '0.0.0.0', port: 8125 },
// repeaterProtocol: 'udp4',
// histogram: [],
// automaticConfigReload: true,
end_of_this_config: 'no_comma'
}
